# Site settings
title: Personal Website 
description: A personal page, blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Wandi Susanto
user_description: Hi, I am Wandi. I am originally from Indonesia. I lived in Saarbruecken and Muenchen, Germany for 10 years. Now I am based in Singapore for next chapter of my journey. I am interested in entrepreneurship, machine learning, deep learning, data science.
user_title: Data Scientist
#email: 
#twitter_username: lorem_ipsum
github_username:  wandikang
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
