# Site settings
title: Personal Website 
description: A personal page, blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Wandi Susanto
user_description: Hi, I am Wandi. I am originally from Indonesia. I studied Computer Science (Machine Learning) in Universität des Saarlandes and Max Planck Institute, Germany. I also lived and worked for a few years in beautiful city München, Germany. Now I am based in Singapore. I am interested in entrepreneurship, machine learning, deep learning, computer vision, data science.
user_title: Data Scientist
#email: 
#twitter_username: lorem_ipsum
github_username:  wandikang
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
